# Generated by Django 4.2.11 on 2026-02-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_add_brand_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
